### PR TITLE
added 'next steps' for a number of methods in the display.yaml

### PR DESCRIPTION
**Pull request by dangunter**

### CODE REVIEW

**Comment by msneddon** [comment]
hey dan- we should just get you commit privileges for sandbox.  We can ask keith today.

**Comment by teharrison** [comment]
What is the appropriate syntax in the yaml file to add a next step.  The
dir name of the method you wish listed?  Can I add more than one next
step?  Do I need to prefix the method name with a dash '-' ?

**Comment by msneddon** [comment]
The IDs of methods/apps are the directory names.  Right now there is no error checking that those are valid ids- something we should add.  You can add more than one- the method store expects them to be a list.  The dash in yaml is one way to indicate a list (or in yaml speak, a collection: http://www.yaml.org/spec/1.2/spec.html#id2759963)

Here are a couple examples that pass tests (yes, the method store actually has tests!): https://github.com/kbase/narrative_method_specs/blob/test/methods/test_method_7/display.yaml#L18
https://github.com/kbase/narrative_method_specs/blob/test/apps/test_app_2/display.yaml#L19

**Comment by dangunter** [comment]
It should be the name of the directory with the display.yaml and spec.json
files in it.
You can add multiple next steps. Any valid YAML syntax for lists of things
(including the bulleted list) should work.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by dangunter** [comment]
I think the 'id' of the method/app should be in either the spec.json or
display.yaml (maybe both). This would allow future storage arrangements of
different kinds to not change the ids.

I am still working on the code to actually use these 'next steps'. It
should be committed some time today.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Pull request merged**
